name: Tensorflow2.x Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install 'tensorflow>2.0'
        pip install -r dev-requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config setup.cfg
    - name: Test with pytest
      run: |
        export TF_KERAS=1; pytest --cov tests
